packages:
  - apps/*
  - infra/*
  - packages/*
allowBuilds:
  esbuild: true
  maplibre-gl@https://codeload.github.com/ljstrnadiii/maplibre-gl-js/tar.gz/51fbd2418ccbaafdc05d0778c9dfc4f546af595a: true
  protobufjs: true
